/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import entidades.*;
import java.util.*;
import datos.*;
import javax.swing.table.DefaultTableModel;
import javax.swing.*;

/**
 *
 * @author Salvattore
 */
public class FormMostrarLibrosPrestados extends javax.swing.JFrame {

    /**
     * Creates new form FormMostrarLibrosPrestados
     */
    public FormMostrarLibrosPrestados() {
        initComponents();
    }

    public FormMostrarLibrosPrestados(Biblioteca biblioteca, JFrame panel) {
        initComponents();
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
    }

    public FormMostrarLibrosPrestados(Biblioteca biblioteca, JFrame panel, int pos) {
        initComponents();
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
        this.pos = pos;
    }

    public void llenarTabla(List<LibroPrestado> lista) {
        modelo = new DefaultTableModel();
        LibroPrestado libro;
        String tipo;

        String columnas[] = {"Código bibliotecario", "Código Prestatario", "Código Libro", "Fecha", "Plazo hasta", "Dentro del plazo"};
        Object fila[] = new Object[columnas.length];
        modelo.setColumnIdentifiers(columnas);
        Iterator<LibroPrestado> iterador = lista.iterator();
        while (iterador.hasNext()) {

            libro = iterador.next();
            fila[0] = libro.getCodigoEmpleado();
            fila[1] = libro.getCodigoCarnet();
            fila[2] = libro.getCodigoLibro();
            fila[3] = libro.getFechaPrestamo().toString();
            fila[4] = libro.getFechaPlazo().toString();
            fila[5] = libro.getDentroDelPlazo() ? "Sí" : "No";
            modelo.addRow(fila);

        }

        tblLibrosPrestados.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scrLibros = new javax.swing.JScrollPane();
        tblLibrosPrestados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rbFecha = new javax.swing.JRadioButton();
        rbCodigoLibro = new javax.swing.JRadioButton();
        rbCodigoPrestatario = new javax.swing.JRadioButton();
        rbCodigoBibliotecario = new javax.swing.JRadioButton();
        btnMostrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar libros prestados");

        scrLibros.setEnabled(false);

        tblLibrosPrestados.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        tblLibrosPrestados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Código bibliotecario", "Código prestatario", "Código libro", "Fecha", "Plazo hasta", "Dentro del plazo"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblLibrosPrestados.setEnabled(false);
        scrLibros.setViewportView(tblLibrosPrestados);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar por"));

        buttonGroup1.add(rbFecha);
        rbFecha.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbFecha.setText("Fecha");

        buttonGroup1.add(rbCodigoLibro);
        rbCodigoLibro.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbCodigoLibro.setText("Código libro");

        buttonGroup1.add(rbCodigoPrestatario);
        rbCodigoPrestatario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbCodigoPrestatario.setText("Codigo prestatario");

        buttonGroup1.add(rbCodigoBibliotecario);
        rbCodigoBibliotecario.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbCodigoBibliotecario.setSelected(true);
        rbCodigoBibliotecario.setText("Código bibliotecario");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCodigoBibliotecario)
                    .addComponent(rbCodigoLibro))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCodigoPrestatario)
                    .addComponent(rbFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCodigoPrestatario, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbCodigoBibliotecario))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbCodigoLibro)
                    .addComponent(rbFecha))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnMostrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(scrLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnMostrar)
                        .addGap(64, 64, 64)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrar)
                            .addComponent(btnVolver))
                        .addGap(28, 28, 28))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(scrLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        lista = biblioteca.getListaLibrosPrestados().getLista();

        if (rbCodigoBibliotecario.isSelected()) {
            Collections.sort(lista);
        } else if (rbCodigoPrestatario.isSelected()) {
            Collections.sort(lista, new CompararLibroPrestadoPorPrestatario());
        } else if (rbFecha.isSelected()) {
            Collections.sort(lista, new CompararLibroPrestadoPorFecha());
        } else if (rbCodigoLibro.isSelected()) {
            Collections.sort(lista, new CompararLibroPrestadoPorLibro());
        }

        llenarTabla(lista);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (pos == -1) {
            new FormPresDirector(biblioteca, this).setVisible(true);
        } else {
            new FormPresBibliotecario(biblioteca, this, pos).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarLibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarLibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarLibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarLibrosPrestados.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormMostrarLibrosPrestados().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbCodigoBibliotecario;
    private javax.swing.JRadioButton rbCodigoLibro;
    private javax.swing.JRadioButton rbCodigoPrestatario;
    private javax.swing.JRadioButton rbFecha;
    private javax.swing.JScrollPane scrLibros;
    private javax.swing.JTable tblLibrosPrestados;
    // End of variables declaration//GEN-END:variables
    private Biblioteca biblioteca;
    private List<LibroPrestado> lista;
    private DefaultTableModel modelo;
    private int pos = -1;
}
