/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.*;
import entidades.*;
import logica.*;
import javax.swing.*;

/**
 *
 * @author Salvattore
 */
public class FormPresDirector extends javax.swing.JFrame {

    /**
     * Creates new form FormPresDirector
     */
    public FormPresDirector() {
        initComponents();
    }

    public FormPresDirector(Biblioteca biblioteca, JFrame panel) {
        initComponents();
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
        llenarCampos();
    }

    public void llenarCampos() {
        Bibliotecario director = biblioteca.getDirector();
        txtNombreD.setText(director.getNombres());
        txtApellidoD.setText(director.getApellidos());
        txtDniD.setText(director.getDni());
        txtTelefonoD.setText(director.getTelefono());
        txtCodigoD.setText(director.getCodigo());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplGerente1 = new javax.swing.JPanel();
        lblNombreG2 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        lblProfesion1 = new javax.swing.JLabel();
        txtCodigoD = new javax.swing.JTextField();
        lblNombreG3 = new javax.swing.JLabel();
        txtApellidoD = new javax.swing.JTextField();
        lblNombreG4 = new javax.swing.JLabel();
        txtDniD = new javax.swing.JTextField();
        txtTelefonoD = new javax.swing.JTextField();
        lblNombreG5 = new javax.swing.JLabel();
        btnRegistrarEmpleado = new javax.swing.JButton();
        btnMostrarBibliotecarios = new javax.swing.JButton();
        btnMostrarLibros = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnMostrarPrestatarios = new javax.swing.JButton();
        btnMostrarBiblioteca = new javax.swing.JButton();
        btnMostrarLibrosPrestados = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Director");

        jplGerente1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del director", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jplGerente1.setEnabled(false);

        lblNombreG2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG2.setText("Nombres:");

        txtNombreD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNombreD.setEnabled(false);

        lblProfesion1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion1.setText("Código:");

        txtCodigoD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtCodigoD.setEnabled(false);

        lblNombreG3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG3.setText("Apellidos:");

        txtApellidoD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtApellidoD.setEnabled(false);
        txtApellidoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoDActionPerformed(evt);
            }
        });

        lblNombreG4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG4.setText("DNI:");

        txtDniD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtDniD.setEnabled(false);

        txtTelefonoD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtTelefonoD.setEnabled(false);

        lblNombreG5.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG5.setText("Teléfono:");

        javax.swing.GroupLayout jplGerente1Layout = new javax.swing.GroupLayout(jplGerente1);
        jplGerente1.setLayout(jplGerente1Layout);
        jplGerente1Layout.setHorizontalGroup(
            jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplGerente1Layout.createSequentialGroup()
                        .addComponent(lblNombreG2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplGerente1Layout.createSequentialGroup()
                        .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreG3)
                            .addComponent(lblNombreG4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplGerente1Layout.createSequentialGroup()
                                .addComponent(txtDniD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(lblNombreG5)
                                .addGap(24, 24, 24)
                                .addComponent(txtTelefonoD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtApellidoD, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jplGerente1Layout.createSequentialGroup()
                        .addComponent(lblProfesion1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)))
                .addContainerGap())
        );
        jplGerente1Layout.setVerticalGroup(
            jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerente1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerente1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        btnRegistrarEmpleado.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrarEmpleado.setText("Registrar bibliotecario");
        btnRegistrarEmpleado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarEmpleadoActionPerformed(evt);
            }
        });

        btnMostrarBibliotecarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrarBibliotecarios.setText("Mostrar bibliotecarios");
        btnMostrarBibliotecarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarBibliotecariosActionPerformed(evt);
            }
        });

        btnMostrarLibros.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrarLibros.setText("Mostrar libros");
        btnMostrarLibros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarLibrosActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setMnemonic('R');
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnMostrarPrestatarios.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrarPrestatarios.setText("Mostrar prestatarios");
        btnMostrarPrestatarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarPrestatariosActionPerformed(evt);
            }
        });

        btnMostrarBiblioteca.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrarBiblioteca.setText("Mostrar biblioteca");
        btnMostrarBiblioteca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarBibliotecaActionPerformed(evt);
            }
        });

        btnMostrarLibrosPrestados.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrarLibrosPrestados.setText("Mostrar libros prestados");
        btnMostrarLibrosPrestados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarLibrosPrestadosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addComponent(btnRegistrarEmpleado)
                        .addGap(56, 56, 56)
                        .addComponent(btnMostrarBibliotecarios)
                        .addGap(43, 43, 43)
                        .addComponent(btnMostrarLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(131, 131, 131)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarLibrosPrestados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnMostrarPrestatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 223, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(86, 86, 86)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnMostrarBiblioteca, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(jplGerente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jplGerente1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrarEmpleado)
                    .addComponent(btnMostrarBibliotecarios)
                    .addComponent(btnMostrarLibros))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarPrestatarios)
                    .addComponent(btnMostrarBiblioteca))
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnMostrarLibrosPrestados)
                    .addComponent(btnVolver))
                .addContainerGap(23, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoDActionPerformed

    private void btnRegistrarEmpleadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoActionPerformed
        new FormRegistrarBibliotecario(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarEmpleadoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FormIngreso(biblioteca).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnMostrarLibrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarLibrosActionPerformed
        new FormMostrarLibros(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMostrarLibrosActionPerformed

    private void btnMostrarPrestatariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarPrestatariosActionPerformed
        new FormMostrarPrestatarios(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMostrarPrestatariosActionPerformed

    private void btnMostrarBibliotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarBibliotecariosActionPerformed
        new FormMostrarBibliotecarios(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMostrarBibliotecariosActionPerformed

    private void btnMostrarBibliotecaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarBibliotecaActionPerformed
        new FormInfoBiblioteca(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMostrarBibliotecaActionPerformed

    private void btnMostrarLibrosPrestadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarLibrosPrestadosActionPerformed
        new FormMostrarLibrosPrestados(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMostrarLibrosPrestadosActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormPresDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormPresDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormPresDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormPresDirector.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormPresDirector().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrarBiblioteca;
    private javax.swing.JButton btnMostrarBibliotecarios;
    private javax.swing.JButton btnMostrarLibros;
    private javax.swing.JButton btnMostrarLibrosPrestados;
    private javax.swing.JButton btnMostrarPrestatarios;
    private javax.swing.JButton btnRegistrarEmpleado;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jplGerente1;
    private javax.swing.JLabel lblNombreG2;
    private javax.swing.JLabel lblNombreG3;
    private javax.swing.JLabel lblNombreG4;
    private javax.swing.JLabel lblNombreG5;
    private javax.swing.JLabel lblProfesion1;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtCodigoD;
    private javax.swing.JTextField txtDniD;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtTelefonoD;
    // End of variables declaration//GEN-END:variables
    private Biblioteca biblioteca;
}
