/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.*;
import entidades.*;
import logica.*;
import javax.swing.*;

/**
 *
 * @author Salvattore
 */
public class FormRegistrarBibliotecario extends javax.swing.JFrame {

    /**
     * Creates new form FormRegistrarBibliotecario
     */
    public FormRegistrarBibliotecario() {
        initComponents();
    }

    public FormRegistrarBibliotecario(Biblioteca biblioteca, JFrame panel) {
        initComponents();
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
        activarCampos(false);
    }

    public void limpiar() {
        txtNombreB.setText("");
        txtApellidoB.setText("");
        txtDniB.setText("");
        txtTelefonoB.setText("");
        txtCodigoB.setText("");
        txtContraseñaB.setText("");
    }

    public void activarCampos(boolean v) {
        txtNombreB.setEnabled(v);
        txtApellidoB.setEnabled(v);
        txtDniB.setEnabled(v);
        txtTelefonoB.setEnabled(v);
        txtCodigoB.setEnabled(v);
        txtContraseñaB.setEnabled(v);
        btnNuevo.setEnabled(!v);
        btnRegistrar.setEnabled(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplGerente = new javax.swing.JPanel();
        lblNombreG = new javax.swing.JLabel();
        txtNombreB = new javax.swing.JTextField();
        lblProfesion = new javax.swing.JLabel();
        txtCodigoB = new javax.swing.JTextField();
        lblProfesion1 = new javax.swing.JLabel();
        lblNombreG1 = new javax.swing.JLabel();
        txtApellidoB = new javax.swing.JTextField();
        lblNombreG2 = new javax.swing.JLabel();
        txtDniB = new javax.swing.JTextField();
        txtTelefonoB = new javax.swing.JTextField();
        lblNombreG3 = new javax.swing.JLabel();
        txtContraseñaB = new javax.swing.JPasswordField();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar bibliotecario");

        jplGerente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del bibliotecario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jplGerente.setEnabled(false);

        lblNombreG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG.setText("Nombres:");

        txtNombreB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblProfesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion.setText("Código:");

        txtCodigoB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblProfesion1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion1.setText("Contraseña:");

        lblNombreG1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG1.setText("Apellidos:");

        txtApellidoB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        txtApellidoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoBActionPerformed(evt);
            }
        });

        lblNombreG2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG2.setText("DNI:");

        txtDniB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        txtTelefonoB.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N

        lblNombreG3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG3.setText("Teléfono:");

        javax.swing.GroupLayout jplGerenteLayout = new javax.swing.GroupLayout(jplGerente);
        jplGerente.setLayout(jplGerenteLayout);
        jplGerenteLayout.setHorizontalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addComponent(lblNombreG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addComponent(lblNombreG1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addComponent(txtApellidoB, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoB)
                            .addComponent(txtContraseñaB, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGap(123, 123, 123))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplGerenteLayout.createSequentialGroup()
                        .addComponent(lblNombreG2)
                        .addGap(18, 18, 18)
                        .addComponent(txtDniB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNombreG3)
                        .addGap(24, 24, 24)
                        .addComponent(txtTelefonoB, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jplGerenteLayout.setVerticalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseñaB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrar.setMnemonic('R');
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNuevo.setMnemonic('R');
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setMnemonic('R');
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(117, 117, 117))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(57, 57, 57)
                    .addComponent(jplGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(54, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnNuevo)
                    .addComponent(btnVolver))
                .addGap(53, 53, 53))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(60, 60, 60)
                    .addComponent(jplGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGap(104, 104, 104)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoBActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombreB.getText().trim(), apellido = txtApellidoB.getText().trim(), telefono = txtTelefonoB.getText().trim(), dni = txtDniB.getText().trim(), codigo = txtCodigoB.getText().trim(), contraseña = txtContraseñaB.getText().trim();
        if (!nombre.equals("") && !apellido.equals("") && !telefono.equals("") && !dni.equals("") && !codigo.equals("") && !contraseña.equals("")) {
            if (!biblioteca.getListaBibliotecarios().CodigoEnUso(codigo) && !biblioteca.getDirector().getCodigo().equals(codigo)) {
                biblioteca.AgregarBibliotecario(new Bibliotecario(nombre, apellido, dni, telefono, codigo, contraseña));
                activarCampos(false);
            } else {
                JOptionPane.showMessageDialog(null, "Código en uso.", "Error", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los valores.", "Error", 0);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        activarCampos(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FormPresDirector(biblioteca, this).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarBibliotecario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormRegistrarBibliotecario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jplGerente;
    private javax.swing.JLabel lblNombreG;
    private javax.swing.JLabel lblNombreG1;
    private javax.swing.JLabel lblNombreG2;
    private javax.swing.JLabel lblNombreG3;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JLabel lblProfesion1;
    private javax.swing.JTextField txtApellidoB;
    private javax.swing.JTextField txtCodigoB;
    private javax.swing.JPasswordField txtContraseñaB;
    private javax.swing.JTextField txtDniB;
    private javax.swing.JTextField txtNombreB;
    private javax.swing.JTextField txtTelefonoB;
    // End of variables declaration//GEN-END:variables
    private Biblioteca biblioteca;
}
