/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.*;
import datos.*;
import entidades.*;
import logica.*;
import javax.swing.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Salvattore
 */
public class FormMostrarPrestatarios extends javax.swing.JFrame {

    /**
     * Creates new form FormMostrarPrestatarios
     */
    public FormMostrarPrestatarios() {
        initComponents();
    }

    public FormMostrarPrestatarios(Biblioteca biblioteca, JFrame panel) {
        initComponents();
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
    }

    public FormMostrarPrestatarios(Biblioteca biblioteca, JFrame panel, int pos) {
        initComponents();
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
        this.pos = pos;
    }

    public void llenarTabla(List<Prestatario> lista) {
        modelo = new DefaultTableModel();
        Prestatario prestatario;
        String tipo;

        String columnas[] = {"Código", "Nombres", "Apellidos", "DNI", "Teléfono", "Dirección", "Libros Prestados"};
        Object fila[] = new Object[columnas.length];
        modelo.setColumnIdentifiers(columnas);
        Iterator<Prestatario> iterador = lista.iterator();
        while (iterador.hasNext()) {
            prestatario = iterador.next();
            fila[0] = prestatario.getCodigoCarnet();
            fila[1] = prestatario.getNombres();
            fila[2] = prestatario.getApellidos();
            fila[3] = prestatario.getDni();
            fila[4] = prestatario.getTelefono();
            fila[5] = prestatario.getDireccion();
            fila[6] = prestatario.getPrestados();
            modelo.addRow(fila);
        }

        tblPrestatarios.setModel(modelo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        scrLibros = new javax.swing.JScrollPane();
        tblPrestatarios = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        rbApellidos = new javax.swing.JRadioButton();
        rbDni = new javax.swing.JRadioButton();
        rbNombre = new javax.swing.JRadioButton();
        rbCodigo = new javax.swing.JRadioButton();
        btnMostrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Mostrar prestatarios");

        scrLibros.setEnabled(false);

        tblPrestatarios.setFont(new java.awt.Font("Times New Roman", 0, 11)); // NOI18N
        tblPrestatarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "Código", "Nombres", "Apellidos", "DNI", "Teléfono", "Dirección", "Libros Prestados"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblPrestatarios.setEnabled(false);
        scrLibros.setViewportView(tblPrestatarios);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar por"));

        buttonGroup1.add(rbApellidos);
        rbApellidos.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbApellidos.setText("Apellidos");

        buttonGroup1.add(rbDni);
        rbDni.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbDni.setText("DNI");

        buttonGroup1.add(rbNombre);
        rbNombre.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbNombre.setText("Nombre");

        buttonGroup1.add(rbCodigo);
        rbCodigo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        rbCodigo.setSelected(true);
        rbCodigo.setText("Código");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbCodigo)
                    .addComponent(rbDni))
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNombre)
                    .addComponent(rbApellidos))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rbNombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(rbCodigo))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbDni)
                    .addComponent(rbApellidos))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        btnMostrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnMostrar.setText("Mostrar");
        btnMostrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(scrLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 884, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(38, 38, 38)
                        .addComponent(btnMostrar)
                        .addGap(64, 64, 64)
                        .addComponent(btnVolver)))
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 11, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrar)
                            .addComponent(btnVolver))
                        .addGap(28, 28, 28)))
                .addComponent(scrLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 297, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnMostrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarActionPerformed
        lista = biblioteca.getListaPrestatarios().getLista();
        boolean re = false;
        ArrayList<Persona> aux = new ArrayList<>();
        Iterator<Prestatario> iterador = lista.iterator();
        while (iterador.hasNext()) {
            aux.add(iterador.next());
        }
        List<Persona> aux2 = aux;

        if (rbCodigo.isSelected()) {
            Collections.sort(lista);
        } else if (rbNombre.isSelected()) {
            Collections.sort(aux2, new CompararPersonaPorNombre());
            re = true;
        } else if (rbApellidos.isSelected()) {
            Collections.sort(aux2, new CompararPersonaPorApellidos());
            re = true;
        } else if (rbDni.isSelected()) {
            Collections.sort(aux2, new CompararPersonaPorDNI());
            re = true;
        }

        if (re) {
            Iterator<Persona> iterador2 = aux2.iterator();
            lista.clear();
            while (iterador2.hasNext()) {
                lista.add(((Prestatario) iterador2.next()));
            }
        }

        llenarTabla(lista);
    }//GEN-LAST:event_btnMostrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (pos == -1) {
            new FormPresDirector(biblioteca, this).setVisible(true);
        } else {
            new FormPresBibliotecario(biblioteca, this, pos).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarPrestatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarPrestatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarPrestatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormMostrarPrestatarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormMostrarPrestatarios().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnMostrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JRadioButton rbApellidos;
    private javax.swing.JRadioButton rbCodigo;
    private javax.swing.JRadioButton rbDni;
    private javax.swing.JRadioButton rbNombre;
    private javax.swing.JScrollPane scrLibros;
    private javax.swing.JTable tblPrestatarios;
    // End of variables declaration//GEN-END:variables

    private Biblioteca biblioteca;
    private List<Prestatario> lista;
    private int pos = -1;
    private DefaultTableModel modelo;
}
