/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.util.*;
import javax.swing.*;
import entidades.*;
import logica.*;

/**
 *
 * @author Salvattore
 */
public class FormInfoBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form FormInfoBiblioteca
     */
    public FormInfoBiblioteca() {
        initComponents();
    }

    public FormInfoBiblioteca(Biblioteca biblioteca, JFrame panel) {
        initComponents();
        this.biblioteca = biblioteca;
        llenarCampos();
        setLocationRelativeTo(panel);
    }

    public FormInfoBiblioteca(Biblioteca biblioteca, JFrame panel, int pos) {
        initComponents();
        this.biblioteca = biblioteca;
        this.pos = pos;
        llenarCampos();
        setLocationRelativeTo(panel);
    }

    public void llenarCampos() {
        txtNombreB.setText(biblioteca.getNombre());
        txtNombreD.setText(biblioteca.getDirector().getNombres() + " " + biblioteca.getDirector().getApellidos());
        txtNumBibliotecarios.setText(Integer.toString(biblioteca.getListaBibliotecarios().getTamaño()));
        txtNumLibros.setText(Integer.toString(biblioteca.getLibrosBiblioteca().getTamaño()));
        txtNumPrestatarios.setText(Integer.toString(biblioteca.getListaPrestatarios().getTamaño()));
        txtNumLibrosPrestados.setText(Integer.toString(biblioteca.getListaLibrosPrestados().getTamaño()));
        txtMultas.setText(Float.toString(biblioteca.getMultas()));

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jplGerente2 = new javax.swing.JPanel();
        lblNombreG6 = new javax.swing.JLabel();
        txtNombreB = new javax.swing.JTextField();
        lblNombreG7 = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        lblNombreG8 = new javax.swing.JLabel();
        txtNumLibros = new javax.swing.JTextField();
        txtNumPrestatarios = new javax.swing.JTextField();
        lblNombreG9 = new javax.swing.JLabel();
        lblNombreG10 = new javax.swing.JLabel();
        txtNumBibliotecarios = new javax.swing.JTextField();
        lblNombreG11 = new javax.swing.JLabel();
        txtNumLibrosPrestados = new javax.swing.JTextField();
        lblNombreG12 = new javax.swing.JLabel();
        txtMultas = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Información biblioteca");

        jplGerente2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos de la biblioteca", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N
        jplGerente2.setEnabled(false);

        lblNombreG6.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG6.setText("Nombre");

        txtNombreB.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNombreB.setEnabled(false);
        txtNombreB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreBActionPerformed(evt);
            }
        });

        lblNombreG7.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG7.setText("Nombre del director");

        txtNombreD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNombreD.setEnabled(false);
        txtNombreD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNombreDActionPerformed(evt);
            }
        });

        lblNombreG8.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG8.setText("Número de libros registrados");

        txtNumLibros.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNumLibros.setEnabled(false);

        txtNumPrestatarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNumPrestatarios.setEnabled(false);
        txtNumPrestatarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumPrestatariosActionPerformed(evt);
            }
        });

        lblNombreG9.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG9.setText("Número de prestatarios registrados");

        lblNombreG10.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG10.setText("Número de bibliotecarios contratados");

        txtNumBibliotecarios.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNumBibliotecarios.setEnabled(false);
        txtNumBibliotecarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNumBibliotecariosActionPerformed(evt);
            }
        });

        lblNombreG11.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG11.setText("Número de libros prestados");

        txtNumLibrosPrestados.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtNumLibrosPrestados.setEnabled(false);

        lblNombreG12.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG12.setText("Cantidad total en razón de multas");

        txtMultas.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtMultas.setEnabled(false);
        txtMultas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMultasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jplGerente2Layout = new javax.swing.GroupLayout(jplGerente2);
        jplGerente2.setLayout(jplGerente2Layout);
        jplGerente2Layout.setHorizontalGroup(
            jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplGerente2Layout.createSequentialGroup()
                        .addComponent(lblNombreG6)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplGerente2Layout.createSequentialGroup()
                        .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addComponent(lblNombreG12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtMultas, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addComponent(lblNombreG11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumLibrosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addComponent(lblNombreG10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addComponent(lblNombreG9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumPrestatarios, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addComponent(lblNombreG8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(txtNumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerente2Layout.createSequentialGroup()
                                .addComponent(lblNombreG7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                                .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(24, 24, 24))))
        );
        jplGerente2Layout.setVerticalGroup(
            jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerente2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG6, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreB, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumBibliotecarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumLibros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtNumPrestatarios, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNumLibrosPrestados, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerente2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG12, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMultas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(48, 48, 48)
                        .addComponent(jplGerente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(251, 251, 251)
                        .addComponent(btnVolver)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jplGerente2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnVolver)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNombreDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreDActionPerformed

    private void txtNombreBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNombreBActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNombreBActionPerformed

    private void txtNumBibliotecariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumBibliotecariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumBibliotecariosActionPerformed

    private void txtNumPrestatariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNumPrestatariosActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNumPrestatariosActionPerformed

    private void txtMultasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMultasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtMultasActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        if (pos == -1) {
            new FormPresDirector(biblioteca, this).setVisible(true);
        } else {
            new FormPresBibliotecario(biblioteca, this, pos).setVisible(true);
        }
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormInfoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormInfoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormInfoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormInfoBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormInfoBiblioteca().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnVolver;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jplGerente2;
    private javax.swing.JLabel lblNombreG10;
    private javax.swing.JLabel lblNombreG11;
    private javax.swing.JLabel lblNombreG12;
    private javax.swing.JLabel lblNombreG6;
    private javax.swing.JLabel lblNombreG7;
    private javax.swing.JLabel lblNombreG8;
    private javax.swing.JLabel lblNombreG9;
    private javax.swing.JTextField txtMultas;
    private javax.swing.JTextField txtNombreB;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtNumBibliotecarios;
    private javax.swing.JTextField txtNumLibros;
    private javax.swing.JTextField txtNumLibrosPrestados;
    private javax.swing.JTextField txtNumPrestatarios;
    // End of variables declaration//GEN-END:variables

    private Biblioteca biblioteca;
    private int pos = -1;
}
