/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.*;
import entidades.*;
import logica.*;
import javax.swing.*;

/**
 *
 * @author Salvattore
 */
public class FormRegistrarPrestatario extends javax.swing.JFrame {

    /**
     * Creates new form FormRegistroPrestatario
     */
    public FormRegistrarPrestatario() {
        initComponents();
    }

    public FormRegistrarPrestatario(Biblioteca biblioteca, JFrame panel, int pos) {
        initComponents();
        this.pos = pos;
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
        activarCampos(false);
    }

    public void limpiar() {
        txtNombreP.setText("");
        txtApellidoP.setText("");
        txtDniP.setText("");
        txtTelefonoP.setText("");
        txtCodigoP.setText("");
        txtDireccionP.setText("");
    }

    public void activarCampos(boolean v) {
        txtNombreP.setEnabled(v);
        txtApellidoP.setEnabled(v);
        txtDniP.setEnabled(v);
        txtTelefonoP.setEnabled(v);
        txtCodigoP.setEnabled(v);
        txtDireccionP.setEnabled(v);
        btnNuevo.setEnabled(!v);
        btnRegistrar.setEnabled(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplGerente = new javax.swing.JPanel();
        lblNombreG = new javax.swing.JLabel();
        txtNombreP = new javax.swing.JTextField();
        lblProfesion = new javax.swing.JLabel();
        txtCodigoP = new javax.swing.JTextField();
        lblProfesion1 = new javax.swing.JLabel();
        lblNombreG1 = new javax.swing.JLabel();
        txtApellidoP = new javax.swing.JTextField();
        lblNombreG2 = new javax.swing.JLabel();
        txtDniP = new javax.swing.JTextField();
        txtTelefonoP = new javax.swing.JTextField();
        lblNombreG3 = new javax.swing.JLabel();
        txtDireccionP = new javax.swing.JTextField();
        btnNuevo = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar prestatario");

        jplGerente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del prestatario", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jplGerente.setEnabled(false);

        lblNombreG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG.setText("Nombres:");

        txtNombreP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblProfesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion.setText("Código carnet:");

        txtCodigoP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblProfesion1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion1.setText("Dirección:");

        lblNombreG1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG1.setText("Apellidos:");

        txtApellidoP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtApellidoP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoPActionPerformed(evt);
            }
        });

        lblNombreG2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG2.setText("DNI:");

        txtDniP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtTelefonoP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblNombreG3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG3.setText("Teléfono:");

        txtDireccionP.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jplGerenteLayout = new javax.swing.GroupLayout(jplGerente);
        jplGerente.setLayout(jplGerenteLayout);
        jplGerenteLayout.setHorizontalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addComponent(lblNombreG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreG1)
                            .addComponent(lblNombreG2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplGerenteLayout.createSequentialGroup()
                                .addComponent(txtDniP, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                                .addComponent(lblNombreG3)
                                .addGap(24, 24, 24)
                                .addComponent(txtTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerenteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoP, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE)
                            .addComponent(txtDireccionP))
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        jplGerenteLayout.setVerticalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 20, Short.MAX_VALUE)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDireccionP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23))
        );

        btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNuevo.setMnemonic('R');
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrar.setMnemonic('R');
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setMnemonic('R');
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jplGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(102, 102, 102)
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101)
                        .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(0, 31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jplGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVolver))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtApellidoPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoPActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoPActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        activarCampos(true);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String nombre = txtNombreP.getText().trim(), apellido = txtApellidoP.getText().trim(), telefono = txtTelefonoP.getText().trim(), dni = txtDniP.getText().trim(), codigo = txtCodigoP.getText().trim(), direccion = txtDireccionP.getText().trim();
        if (!nombre.equals("") && !apellido.equals("") && !telefono.equals("") && !dni.equals("") && !codigo.equals("") && !direccion.equals("")) {

            if (!biblioteca.getListaPrestatarios().CodigoEnUso(codigo)) {
                biblioteca.AgregarPrestatario(new Prestatario(nombre, apellido, dni, telefono, codigo, direccion));
                activarCampos(false);
            } else {
                JOptionPane.showMessageDialog(null, "Código en uso.", "Error", 0);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los valores.", "Error", 0);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FormPresBibliotecario(biblioteca, this, pos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarPrestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarPrestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarPrestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarPrestatario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormRegistrarPrestatario().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JPanel jplGerente;
    private javax.swing.JLabel lblNombreG;
    private javax.swing.JLabel lblNombreG1;
    private javax.swing.JLabel lblNombreG2;
    private javax.swing.JLabel lblNombreG3;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JLabel lblProfesion1;
    private javax.swing.JTextField txtApellidoP;
    private javax.swing.JTextField txtCodigoP;
    private javax.swing.JTextField txtDireccionP;
    private javax.swing.JTextField txtDniP;
    private javax.swing.JTextField txtNombreP;
    private javax.swing.JTextField txtTelefonoP;
    // End of variables declaration//GEN-END:variables
    private Biblioteca biblioteca;
    private int pos;
}
