/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.*;
import entidades.*;
import logica.*;
import javax.swing.*;

/**
 *
 * @author Salvattore
 */
public class FormCreacionBiblioteca extends javax.swing.JFrame {

    /**
     * Creates new form FormCreacionBiblioteca
     */
    public FormCreacionBiblioteca() {
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        jplGerente = new javax.swing.JPanel();
        lblNombreG = new javax.swing.JLabel();
        txtNombreD = new javax.swing.JTextField();
        lblProfesion = new javax.swing.JLabel();
        txtCodigoD = new javax.swing.JTextField();
        lblProfesion1 = new javax.swing.JLabel();
        lblNombreG1 = new javax.swing.JLabel();
        txtApellidoD = new javax.swing.JTextField();
        lblNombreG2 = new javax.swing.JLabel();
        txtDniD = new javax.swing.JTextField();
        txtTelefonoD = new javax.swing.JTextField();
        lblNombreG3 = new javax.swing.JLabel();
        txtContraseñaD = new javax.swing.JPasswordField();
        btnSalir = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Creación de biblioteca");
        setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        jLabel2.setText("Nombre de la biblioteca:");

        txtNombre.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        jplGerente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del director", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jplGerente.setEnabled(false);

        lblNombreG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG.setText("Nombres:");

        txtNombreD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblProfesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion.setText("Código:");

        txtCodigoD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblProfesion1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion1.setText("Contraseña:");

        lblNombreG1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG1.setText("Apellidos:");

        txtApellidoD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        txtApellidoD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtApellidoDActionPerformed(evt);
            }
        });

        lblNombreG2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG2.setText("DNI:");

        txtDniD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        txtTelefonoD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        lblNombreG3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG3.setText("Teléfono:");

        txtContraseñaD.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N

        javax.swing.GroupLayout jplGerenteLayout = new javax.swing.GroupLayout(jplGerente);
        jplGerente.setLayout(jplGerenteLayout);
        jplGerenteLayout.setHorizontalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addComponent(lblNombreG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreG1)
                            .addComponent(lblNombreG2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jplGerenteLayout.createSequentialGroup()
                                .addComponent(txtDniD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                .addComponent(lblNombreG3)
                                .addGap(24, 24, 24)
                                .addComponent(txtTelefonoD, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerenteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtCodigoD)
                            .addComponent(txtContraseñaD, javax.swing.GroupLayout.DEFAULT_SIZE, 240, Short.MAX_VALUE))
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        jplGerenteLayout.setVerticalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNombreD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtApellidoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTelefonoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDniD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtContraseñaD, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        btnSalir.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrar.setMnemonic('R');
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(79, 79, 79)
                        .addComponent(jLabel2)
                        .addGap(109, 109, 109)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(67, 67, 67)
                        .addComponent(jplGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(56, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82)
                .addComponent(btnSalir)
                .addGap(215, 215, 215))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jplGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistrar)
                    .addComponent(btnSalir))
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        if (!txtNombre.getText().trim().equals("") && !txtNombreD.getText().trim().equals("") && !txtApellidoD.getText().trim().equals("")
                && !txtDniD.getText().trim().equals("") && !txtCodigoD.getText().trim().equals("") && !txtContraseñaD.getText().trim().equals("")
                && !txtTelefonoD.getText().trim().equals("")) {
            biblioteca = new Biblioteca();
            biblioteca.setNombre(txtNombre.getText().trim());
            biblioteca.setDirector(new Bibliotecario(txtNombreD.getText().trim(), txtApellidoD.getText().trim(),
                    txtDniD.getText().trim(), txtTelefonoD.getText().trim(), txtCodigoD.getText().trim(), txtContraseñaD.getText().trim()));
            registrado = true;
            biblioteca.escribirBiblioteca(biblioteca);
            activar();
            this.dispose();
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese los valores.", "Error", 0);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void txtApellidoDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtApellidoDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtApellidoDActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        if (!biblioteca.recuperarBiblioteca()) {
            /* Set the Nimbus look and feel */
            //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
            /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
             */
            try {
                for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                    if ("Nimbus".equals(info.getName())) {
                        javax.swing.UIManager.setLookAndFeel(info.getClassName());
                        break;
                    }
                }
            } catch (ClassNotFoundException ex) {
                java.util.logging.Logger.getLogger(FormCreacionBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (InstantiationException ex) {
                java.util.logging.Logger.getLogger(FormCreacionBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (IllegalAccessException ex) {
                java.util.logging.Logger.getLogger(FormCreacionBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            } catch (javax.swing.UnsupportedLookAndFeelException ex) {
                java.util.logging.Logger.getLogger(FormCreacionBiblioteca.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
            }
            //</editor-fold>

            /* Create and display the form */
            java.awt.EventQueue.invokeLater(new Runnable() {
                public void run() {
                    new FormCreacionBiblioteca().setVisible(true);
                }
            });
        } else {
            activar();
        }
    }

    public static void activar() {
        new FormIngreso(biblioteca).setVisible(true);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jplGerente;
    private javax.swing.JLabel lblNombreG;
    private javax.swing.JLabel lblNombreG1;
    private javax.swing.JLabel lblNombreG2;
    private javax.swing.JLabel lblNombreG3;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JLabel lblProfesion1;
    private javax.swing.JTextField txtApellidoD;
    private javax.swing.JTextField txtCodigoD;
    private javax.swing.JPasswordField txtContraseñaD;
    private javax.swing.JTextField txtDniD;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreD;
    private javax.swing.JTextField txtTelefonoD;
    // End of variables declaration//GEN-END:variables
    private static Biblioteca biblioteca = new Biblioteca();
    private static boolean registrado = false;

}
