/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import datos.*;
import entidades.*;
import logica.*;
import javax.swing.*;

/**
 *
 * @author Salvattore
 */
public class FormRegistrarLibro extends javax.swing.JFrame {

    /**
     * Creates new form FormRegistrarLibro
     */
    public FormRegistrarLibro() {
        initComponents();
        activarCampos(false);
    }

    public FormRegistrarLibro(Biblioteca biblioteca, JFrame panel, int pos) {
        initComponents();
        this.pos = pos;
        this.biblioteca = biblioteca;
        setLocationRelativeTo(panel);
        activarCampos(false);
    }

    public void AgregarGenerosLibro() {
        cbxGeneroL.removeAllItems();
        cbxGeneroL.addItem("Acción");
        cbxGeneroL.addItem("Aventura");
        cbxGeneroL.addItem("Comedia");
        cbxGeneroL.addItem("Drama");
        cbxGeneroL.addItem("Poema");
        cbxGeneroL.addItem("Romance");
        cbxGeneroL.addItem("Teatro");
        cbxGeneroL.setSelectedIndex(-1);
    }

    public void AgregarGenerosAcademico() {
        cbxGeneroL.removeAllItems();
        cbxGeneroL.addItem("Ensayo");
        cbxGeneroL.addItem("Informe");
        cbxGeneroL.addItem("Monografía");
        cbxGeneroL.addItem("Reseña");
        cbxGeneroL.addItem("Resumen");
        cbxGeneroL.addItem("Tesis");
        cbxGeneroL.setSelectedIndex(-1);
    }

    public void limpiar() {
        cbxTipoL.setSelectedIndex(-1);
        txtTituloL.setText("");
        txtAutorL.setText("");
        txtAñoL.setText("");
        cbxGeneroL.setSelectedIndex(-1);
        txtEditorialL.setText("");
        txtUniversidadL.setText("");
        txtCodigoL.setText("");
        txtCantidadL.setText("");
    }

    public void activarCampos(boolean v) {
        cbxTipoL.setEnabled(v);
        txtCantidadL.setEnabled(v);
        txtTituloL.setEnabled(v);
        txtAutorL.setEnabled(v);
        txtAñoL.setEnabled(v);
        cbxGeneroL.setEnabled(v);
        txtCodigoL.setEnabled(v);
        txtEditorialL.setEnabled(v);
        txtUniversidadL.setEnabled(v);
        btnRegistrar.setEnabled(v);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplGerente = new javax.swing.JPanel();
        lblNombreG = new javax.swing.JLabel();
        txtTituloL = new javax.swing.JTextField();
        lblProfesion = new javax.swing.JLabel();
        txtEditorialL = new javax.swing.JTextField();
        lblProfesion1 = new javax.swing.JLabel();
        lblNombreG1 = new javax.swing.JLabel();
        txtAutorL = new javax.swing.JTextField();
        lblNombreG2 = new javax.swing.JLabel();
        txtAñoL = new javax.swing.JTextField();
        lblNombreG3 = new javax.swing.JLabel();
        cbxGeneroL = new javax.swing.JComboBox<>();
        lblUniversidad = new javax.swing.JLabel();
        txtUniversidadL = new javax.swing.JTextField();
        txtCodigoL = new javax.swing.JTextField();
        btnVolver = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        btnNuevo = new javax.swing.JButton();
        lblNombreG4 = new javax.swing.JLabel();
        cbxTipoL = new javax.swing.JComboBox<>();
        txtCantidadL = new javax.swing.JTextField();
        lblCantidadL = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Registrar libro");

        jplGerente.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos del libro", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        jplGerente.setEnabled(false);

        lblNombreG.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG.setText("Título:");

        txtTituloL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblProfesion.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion.setText("Editorial:");

        txtEditorialL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblProfesion1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblProfesion1.setText("Código:");

        lblNombreG1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG1.setText("Autor:");

        txtAutorL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtAutorL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAutorLActionPerformed(evt);
            }
        });

        lblNombreG2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG2.setText("Año:");

        txtAñoL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        lblNombreG3.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG3.setText("Género:");

        cbxGeneroL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxGeneroL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxGeneroLActionPerformed(evt);
            }
        });

        lblUniversidad.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblUniversidad.setText("Universidad:");

        txtUniversidadL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        txtCodigoL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        javax.swing.GroupLayout jplGerenteLayout = new javax.swing.GroupLayout(jplGerente);
        jplGerente.setLayout(jplGerenteLayout);
        jplGerenteLayout.setHorizontalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addComponent(lblNombreG)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTituloL, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNombreG1)
                            .addComponent(lblNombreG2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jplGerenteLayout.createSequentialGroup()
                                .addComponent(txtAñoL, javax.swing.GroupLayout.PREFERRED_SIZE, 169, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(lblNombreG3)
                                .addGap(40, 40, 40)
                                .addComponent(cbxGeneroL, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jplGerenteLayout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(txtAutorL, javax.swing.GroupLayout.PREFERRED_SIZE, 361, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplGerenteLayout.createSequentialGroup()
                        .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jplGerenteLayout.createSequentialGroup()
                                .addComponent(lblUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtUniversidadL))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jplGerenteLayout.createSequentialGroup()
                                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblProfesion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtEditorialL, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtCodigoL))))
                        .addGap(123, 123, 123)))
                .addContainerGap())
        );
        jplGerenteLayout.setVerticalGroup(
            jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplGerenteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtTituloL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAutorL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombreG2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNombreG3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAñoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cbxGeneroL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtEditorialL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblUniversidad, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtUniversidadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jplGerenteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProfesion1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtCodigoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29))
        );

        btnVolver.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnVolver.setMnemonic('R');
        btnVolver.setText("Volver");
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });

        btnRegistrar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnRegistrar.setMnemonic('R');
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnNuevo.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        btnNuevo.setMnemonic('R');
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        lblNombreG4.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblNombreG4.setText("Tipo:");

        cbxTipoL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        cbxTipoL.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Libro", "Revista", "Académico" }));
        cbxTipoL.setSelectedIndex(-1);
        cbxTipoL.setEnabled(false);
        cbxTipoL.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbxTipoLItemStateChanged(evt);
            }
        });

        txtCantidadL.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txtCantidadL.setEnabled(false);

        lblCantidadL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblCantidadL.setText("Cantidad:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(101, 101, 101)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(btnVolver, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jplGerente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(81, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblNombreG4)
                        .addGap(47, 47, 47)
                        .addComponent(cbxTipoL, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblCantidadL)
                        .addGap(29, 29, 29)
                        .addComponent(txtCantidadL, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(101, 101, 101))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCantidadL, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(txtCantidadL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblNombreG4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cbxTipoL, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(jplGerente, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNuevo)
                    .addComponent(btnRegistrar)
                    .addComponent(btnVolver))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAutorLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAutorLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAutorLActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        new FormPresBibliotecario(biblioteca, this, pos).setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String titulo = txtTituloL.getText().trim(), autor = txtAutorL.getText().trim(), editorial = txtEditorialL.getText().trim(), año = txtAñoL.getText().trim(), codigo = txtCodigoL.getText().trim(), universidad = txtUniversidadL.getText().trim();
        String genero;
        autor = autor.equals("") ? "Anónimo" : autor;
        editorial = editorial.equals("") ? "Desconocido" : editorial;
        universidad = universidad.equals("") ? "Desconocido" : universidad;
        año = año.equals("") ? "Desconocido" : año;

        try {
            if (cbxGeneroL.getSelectedIndex() > -1) {
            genero = cbxGeneroL.getItemAt(cbxGeneroL.getSelectedIndex());
            }
            else {
                genero = "Desconocido";
            }
        } catch (Exception e) {
            genero = "Desconocido";
        }
        int cantidad;

        try {
            cantidad = Integer.parseInt(txtCantidadL.getText().trim());
        } catch (Exception e) {
            cantidad = 0;
        }

        int tipo = cbxTipoL.getSelectedIndex();
        Documento documento = new Documento();

        switch (tipo) {
            case 0:
                documento = new Libro(autor, titulo, año, genero, editorial);
                break;
            case 1:
                documento = new Revista(autor, titulo, año, editorial);
                break;
            case 2:
                documento = new Academico(autor, titulo, año, universidad, genero);
                break;
        }

        try {
            if (!titulo.equals("") && !codigo.equals("")) {
                if (!biblioteca.getLibrosBiblioteca().CodigoEnUso(codigo)) {
                    if (cantidad > 0) {

                        LibroBiblioteca libro = new LibroBiblioteca();

                        biblioteca.AgregarLibroBiblioteca(new LibroBiblioteca(codigo, documento, cantidad));
                        activarCampos(false);
                        btnNuevo.setEnabled(true);

                    } else {
                        JOptionPane.showMessageDialog(null, "Ingrese una cantidad válida.", "Error", 0);
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Código en uso.", "Error", 0);
                }
            } else {
                JOptionPane.showMessageDialog(null, "Ingrese los valores.", "Error", 0);
            }
        } catch (Exception e) {
            System.out.println(e.getMessage());
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        limpiar();
        cbxTipoL.setEnabled(true);
        txtCantidadL.setEnabled(true);
        btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void cbxTipoLItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbxTipoLItemStateChanged
        int pos = cbxTipoL.getSelectedIndex();
        if (pos != -1) {
            activarCampos(true);
            switch (pos) {
                case 0:
                    txtUniversidadL.setEnabled(false);
                    AgregarGenerosLibro();
                    break;
                case 1:
                    cbxGeneroL.removeAllItems();
                    txtUniversidadL.setEnabled(false);
                    cbxGeneroL.setEnabled(false);
                    break;
                case 2:
                    txtEditorialL.setEnabled(false);
                    AgregarGenerosAcademico();
                    break;
            }
        } else {
            activarCampos(false);
        }
    }//GEN-LAST:event_cbxTipoLItemStateChanged

    private void cbxGeneroLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxGeneroLActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbxGeneroLActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FormRegistrarLibro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FormRegistrarLibro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxGeneroL;
    private javax.swing.JComboBox<String> cbxTipoL;
    private javax.swing.JPanel jplGerente;
    private javax.swing.JLabel lblCantidadL;
    private javax.swing.JLabel lblNombreG;
    private javax.swing.JLabel lblNombreG1;
    private javax.swing.JLabel lblNombreG2;
    private javax.swing.JLabel lblNombreG3;
    private javax.swing.JLabel lblNombreG4;
    private javax.swing.JLabel lblProfesion;
    private javax.swing.JLabel lblProfesion1;
    private javax.swing.JLabel lblUniversidad;
    private javax.swing.JTextField txtAutorL;
    private javax.swing.JTextField txtAñoL;
    private javax.swing.JTextField txtCantidadL;
    private javax.swing.JTextField txtCodigoL;
    private javax.swing.JTextField txtEditorialL;
    private javax.swing.JTextField txtTituloL;
    private javax.swing.JTextField txtUniversidadL;
    // End of variables declaration//GEN-END:variables
    private Biblioteca biblioteca;
    private int pos;
}
